name: 'DiffCache'
author: 'Kamil Rybacki'
description: 'Finds files that have changed since last SUCCESSFUL workflow.'
branding:
  icon: 'eye'
  color: 'green'
inputs:
  cache_secret:
    description: 'Secret containing the cache.'
    required: true
  token:
    description: 'Github token to use for the API calls.'
    required: true
  include:
    description: 'Regex to use to match the files to include. If left empty - all changed files will be included.'
    required: false
  exclude:
    description: 'Regex to use to match the files to ignore. If left empty - no files will be ignored.'
    required: false
  disable_escaping:
    description: 'Set to true if You want to provide manually escaped regexps i.e. turn off manual escape of special characters.'
    required: false
    default: 'false'
outputs:
  files:
    description: 'List of changed files kept as GH Workflow output for convenience.'
runs:
  using: 'node16'
  pre: 'dist/pre/index.js'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
  post-if: success()
